name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          # Remove the cache option since there's no lock file
      
      - name: Install dependencies
        run: |
          npm install -g npm@11.2.0
          # Generate a package-lock.json file for future runs
          npm i --package-lock-only
      
      - name: Build
        run: |
          npm run build
        env:
          # Disable strict mode for build
          NODE_ENV: production
          CI: false
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages

