name: Deploy to GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: |
          npm install -g npm@11.2.0
          npm install --force
          npm install react-hook-form cmdk embla-carousel-react recharts react-day-picker vaul
          npm install clsx @radix-ui/react-accordion @radix-ui/react-alert-dialog @radix-ui/react-aspect-ratio @radix-ui/react-avatar @radix-ui/react-checkbox @radix-ui/react-collapsible @radix-ui/react-dialog @radix-ui/react-context-menu vaul @radix-ui/react-dropdown-menu react-hook-form @radix-ui/react-hover-card input-otp @radix-ui/react-menubar @radix-ui/react-navigation-menu @radix-ui/react-popover @radix-ui/react-progress @radix-ui/react-radio-group react-resizable-panels @radix-ui/react-scroll-area @radix-ui/react-select @radix-ui/react-separator @radix-ui/react-slider sonner @radix-ui/react-switch @radix-ui/react-tabs @radix-ui/react-toast @radix-ui/react-toggle-group @radix-ui/react-toggle @radix-ui/react-tooltip
          npm install @radix-ui/react-accordion @radix-ui/react-alert-dialog @radix-ui/react-aspect-ratio @radix-ui/react-avatar @radix-ui/react-checkbox
          npm install class-variance-authority @radix-ui/react-slot @radix-ui/react-label @radix-ui/react-toast @radix-ui/react-context-menu @radix-ui/react-dropdown-menu
         
      - name: Build and Export
        run: |
          npm run build
        env:
          NODE_ENV: production
          CI: false

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: true
          single-commit: true
          folder: out
          cname: ghazanfaridrees.com
